/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * RetrievalOfSharedDataApi.c
 *
 *
 */

#include "jsonParser.hpp"

#include <nghttp2/asio_http2_server.h>

#include "RetrievalOfSharedDataApi.h"
#include "RetrievalOfSharedDataApiImpl.h"

using namespace nghttp2::asio_http2::server;
using namespace nghttp2::asio_http2;

#include "ProblemDetails.h"
#include "Set.h"
#include "SharedData.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

void RetrievalOfSharedDataApi::get_shared_data_handler(request &requestIn,
                                                       response &responseIn) {

  // Getting the query params
  std::map<std::string, std::string> queryMap;
  if (!requestIn.uri().raw_query.empty()) {
    queryMap = getQueryMap::get(requestIn.uri().raw_query);
  }

  std::string sharedDataIdsQuery;

  if (queryMap.count("shared-data-ids")) {
    sharedDataIdsQuery = (queryMap).at("shared-data-ids");
  }
  std::vector<std::string> sharedDataIds;

  //<param name="sharedDataIds">List of shared data ids parameter type
  //Set<std::string> </param>

  if (!sharedDataIdsQuery.empty()) {
    staticjson::ParseStatus result;
    auto ret = sharedDataIds.decode(sharedDataIdsQuery, result);
    std::cout << "validation report is :" << ret.second << std::endl;
    std::cout << "parse result: " << (int)ret.first << std::endl;
    // std::move(sharedDataIdsQuery)
  }

  std::string supportedFeaturesQuery;

  if (queryMap.count("supportedFeatures")) {
    supportedFeaturesQuery = (queryMap).at("supportedFeatures");
  }
  std::optional<std::string> supportedFeatures;

  //<param name="supportedFeatures">Supported Features parameter type
  //std::string   (optional, default to &quot;&quot;)</param>

  // PrimitiveType
  if (!supportedFeaturesQuery.empty()) {
    supportedFeatures.emplace(supportedFeaturesQuery);
  }

  // Getting the header params
  std::string ifNoneMatch;
  if (requestIn.header().count("If-None-Match")) {
    ifNoneMatch = requestIn.header()["If-None-Match"].value;
  }
  std::string ifModifiedSince;
  if (requestIn.header().count("If-Modified-Since")) {
    ifModifiedSince = requestIn.header()["If-Modified-Since"].value;
  }

  // Getting the header params
  std::string ifNoneMatch;
  if (requestIn.header().count("If-None-Match")) {
    ifNoneMatch = requestIn.header()["If-None-Match"].value;
  }
  std::string ifModifiedSince;
  if (requestIn.header().count("If-Modified-Since")) {
    ifModifiedSince = requestIn.header()["If-Modified-Since"].value;
  }

  try {
    /// <param name="sharedDataIds">List of shared data ids</param>
    /// <param name="supportedFeatures">Supported Features (optional, default to
    /// &quot;&quot;)</param> <param name="ifNoneMatch">Validator for
    /// conditional requests, as described in RFC 7232, 3.2 (optional, default
    /// to &quot;&quot;)</param> <param name="ifModifiedSince">Validator for
    /// conditional requests, as described in RFC 7232, 3.3 (optional, default
    /// to &quot;&quot;)</param>
    RetrievalOfSharedDataApiImpl::get_shared_data(
        sharedDataIds, supportedFeatures, ifNoneMatch, ifModifiedSince,
        requestIn, responseIn);

  } catch (std::exception &e) {
    responseIn.write_head(500);
    responseIn.end(e.what());
    // send a 500 error
    return;
  }
}

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org
