/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SubscriptionDeletionApi.h
 *
 *
 */

#ifndef SubscriptionDeletionApi_H_
#define SubscriptionDeletionApi_H_

#include "jsonParser.hpp"

#include <nghttp2/asio_http2_server.h>

#include "SubscriptionDeletionApiImpl.h"

using namespace nghttp2::asio_http2::server;

#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class SubscriptionDeletionApi {
public:
  SubscriptionDeletionApi();
  virtual ~SubscriptionDeletionApi() {}

  static void unsubscribe_handler(request &requestIn, response &responseIn);
};

} // namespace api
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* SubscriptionDeletionApi_H_ */
