/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TriggerSORInfoUpdateApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_TriggerSORInfoUpdateApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_TriggerSORInfoUpdateApi_H_


#include "../ApiClient.h"

#include "ProblemDetails.h"
#include "SorInfo.h"
#include "SorUpdateInfo.h"
#include <cpprest/details/basic_types.h>


#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  TriggerSORInfoUpdateApi 
{
public:

    explicit TriggerSORInfoUpdateApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~TriggerSORInfoUpdateApi();

    /// <summary>
    /// Nudm_Sdm custom operation to trigger SOR info update
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="supi">Identifier of the UE</param>
    /// <param name="sorUpdateInfo"> (optional)</param>
    pplx::task<std::shared_ptr<SorInfo>> update_SOR_Info(
        utility::string_t supi,
        boost::optional<std::shared_ptr<SorUpdateInfo>> sorUpdateInfo
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_TriggerSORInfoUpdateApi_H_ */

