/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UEContextInAMFDataRetrievalApi.h
 *
 * 
 */

#ifndef UEContextInAMFDataRetrievalApi_H_
#define UEContextInAMFDataRetrievalApi_H_






#include "UEContextInAMFDataRetrievalApiImpl.h"

#include "ProblemDetails.h"
#include "UeContextInAmfData.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class  UEContextInAMFDataRetrievalApi {
public:
    UEContextInAMFDataRetrievalApi();
    virtual ~UEContextInAMFDataRetrievalApi() {}
 



private:
   

    static void get_ue_ctx_in_amf_data_handler(request &requestIn,  response responseIn)
    {
    // Getting the path params
    std::string supi;

    if(request.param.count("supi"))
    {
      supi = request.param["supi"];
    }
    
    
    
    // Getting the query params
    auto supportedFeaturesQuery = request.uri().get("supported-features");
    std::optional<std::string> supportedFeatures;

    if(!supportedFeaturesQuery.isEmpty()){
      supportedFeatures = supportedFeaturesQuery;
    }
    

    try {
    /// <param name="supi">Identifier of the UE</param>
    /// <param name="supportedFeatures">Supported Features (optional, default to &quot;&quot;)</param>
      UEContextInAMFDataRetrievalApiImpl::get_ue_ctx_in_amf_data(supi, supportedFeatures, response);
   
    }  catch (std::exception &e) {
        responseIn.write_head(500);
        responseIn.end(e.what());
        //send a 500 error
        return;
    }
    }
   
 

};

}
}
}
}

#endif /* UEContextInAMFDataRetrievalApi_H_ */

