/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AcknowledgeInfo.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AcknowledgeInfo_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AcknowledgeInfo_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  AcknowledgeInfo
    : public ModelBase
{
public:
    AcknowledgeInfo();
    virtual ~AcknowledgeInfo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// AcknowledgeInfo members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSorMacIue() const;
    bool sorMacIueIsSet() const;
    void unsetSorMacIue();

    void setSorMacIue(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUpuMacIue() const;
    bool upuMacIueIsSet() const;
    void unsetUpuMacIue();

    void setUpuMacIue(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSecuredPacket() const;
    bool securedPacketIsSet() const;
    void unsetSecuredPacket();

    void setSecuredPacket(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getProvisioningTime() const;
    bool provisioningTimeIsSet() const;
    void unsetProvisioningTime();

    void setProvisioningTime(const utility::datetime& value);


protected:
    utility::string_t m_SorMacIue;
    bool m_SorMacIueIsSet;
    utility::string_t m_UpuMacIue;
    bool m_UpuMacIueIsSet;
    utility::string_t m_SecuredPacket;
    bool m_SecuredPacketIsSet;
    utility::datetime m_ProvisioningTime;
    bool m_ProvisioningTimeIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AcknowledgeInfo_H_ */
