/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AcsInfo.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AcsInfo_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AcsInfo_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  AcsInfo
    : public ModelBase
{
public:
    AcsInfo();
    virtual ~AcsInfo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// AcsInfo members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAcsUrl() const;
    bool acsUrlIsSet() const;
    void unsetAcsUrl();

    void setAcsUrl(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAcsIpv4Addr() const;
    bool acsIpv4AddrIsSet() const;
    void unsetAcsIpv4Addr();

    void setAcsIpv4Addr(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAcsIpv6Addr() const;
    bool acsIpv6AddrIsSet() const;
    void unsetAcsIpv6Addr();

    void setAcsIpv6Addr(const utility::string_t& value);


protected:
    utility::string_t m_AcsUrl;
    bool m_AcsUrlIsSet;
    utility::string_t m_AcsIpv4Addr;
    bool m_AcsIpv4AddrIsSet;
    utility::string_t m_AcsIpv6Addr;
    bool m_AcsIpv6AddrIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AcsInfo_H_ */
