/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ChangeType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



ChangeType::ChangeType()
{
}

ChangeType::~ChangeType()
{
}

void ChangeType::validate()
{
    // TODO: implement validation
}

web::json::value ChangeType::toJson() const
{
    web::json::value val = web::json::value::object();

    
    if (m_value == eChangeType::ChangeType_ADD) val = web::json::value::string(U(ADD));
    if (m_value == eChangeType::ChangeType_MOVE) val = web::json::value::string(U(MOVE));
    if (m_value == eChangeType::ChangeType_REMOVE) val = web::json::value::string(U(REMOVE));
    if (m_value == eChangeType::ChangeType_REPLACE) val = web::json::value::string(U(REPLACE));

    return val;
}

bool ChangeType::fromJson(const web::json::value& val)
{
    auto s = val.as_string();

    
    if (s == utility::conversions::to_string_t(ADD)) m_value = eChangeType::ChangeType_ADD;
    if (s == utility::conversions::to_string_t(MOVE)) m_value = eChangeType::ChangeType_MOVE;
    if (s == utility::conversions::to_string_t(REMOVE)) m_value = eChangeType::ChangeType_REMOVE;
    if (s == utility::conversions::to_string_t(REPLACE)) m_value = eChangeType::ChangeType_REPLACE;
    return true;
}

void ChangeType::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    utility::string_t s;

    
    if (m_value == eChangeType::ChangeType_ADD) s = utility::conversions::to_string_t(ADD);
    if (m_value == eChangeType::ChangeType_MOVE) s = utility::conversions::to_string_t(MOVE);
    if (m_value == eChangeType::ChangeType_REMOVE) s = utility::conversions::to_string_t(REMOVE);
    if (m_value == eChangeType::ChangeType_REPLACE) s = utility::conversions::to_string_t(REPLACE);

    multipart->add(ModelBase::toHttpContent(namePrefix, s));
}

bool ChangeType::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    {
        utility::string_t s;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), s);
        eChangeType v;

        
        if (s == utility::conversions::to_string_t(ADD)) v = eChangeType::ChangeType_ADD;
        if (s == utility::conversions::to_string_t(MOVE)) v = eChangeType::ChangeType_MOVE;
        if (s == utility::conversions::to_string_t(REMOVE)) v = eChangeType::ChangeType_REMOVE;
        if (s == utility::conversions::to_string_t(REPLACE)) v = eChangeType::ChangeType_REPLACE;

        setValue(v);
    }
    return ok;
}

ChangeType::eChangeType ChangeType::getValue() const
{
   return m_value;
}

void ChangeType::setValue(ChangeType::eChangeType const value)
{
   m_value = value;
}


}
}
}
}


