/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EllipsoidArc.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_EllipsoidArc_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_EllipsoidArc_H_


#include "GeographicalCoordinates.h"
#include "EllipsoidArc_allOf.h"
#include "GADShape.h"
#include "SupportedGADShapes.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  EllipsoidArc
    : public GADShape
{
public:
    EllipsoidArc();
    virtual ~EllipsoidArc();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// EllipsoidArc members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<GeographicalCoordinates> getPoint() const;
    bool pointIsSet() const;
    void unsetPoint();

    void setPoint(const std::shared_ptr<GeographicalCoordinates>& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getInnerRadius() const;
    bool innerRadiusIsSet() const;
    void unsetInnerRadius();

    void setInnerRadius(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    float getUncertaintyRadius() const;
    bool uncertaintyRadiusIsSet() const;
    void unsetUncertaintyRadius();

    void setUncertaintyRadius(float value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getOffsetAngle() const;
    bool offsetAngleIsSet() const;
    void unsetOffsetAngle();

    void setOffsetAngle(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getIncludedAngle() const;
    bool includedAngleIsSet() const;
    void unsetIncludedAngle();

    void setIncludedAngle(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getConfidence() const;
    bool confidenceIsSet() const;
    void unsetConfidence();

    void setConfidence(int32_t value);


protected:
    std::shared_ptr<GeographicalCoordinates> m_Point;
    bool m_PointIsSet;
    int32_t m_InnerRadius;
    bool m_InnerRadiusIsSet;
    float m_UncertaintyRadius;
    bool m_UncertaintyRadiusIsSet;
    int32_t m_OffsetAngle;
    bool m_OffsetAngleIsSet;
    int32_t m_IncludedAngle;
    bool m_IncludedAngleIsSet;
    int32_t m_Confidence;
    bool m_ConfidenceIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_EllipsoidArc_H_ */
