/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ExternalUnrelatedClass.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ExternalUnrelatedClass_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ExternalUnrelatedClass_H_


#include "../ModelBase.h"

#include "LcsClientGroupExternal.h"
#include "AfExternal.h"
#include <vector>
#include "LcsClientExternal.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  ExternalUnrelatedClass
    : public ModelBase
{
public:
    ExternalUnrelatedClass();
    virtual ~ExternalUnrelatedClass();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ExternalUnrelatedClass members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<LcsClientExternal>>& getLcsClientExternals();
    bool lcsClientExternalsIsSet() const;
    void unsetLcsClientExternals();

    void setLcsClientExternals(const std::vector<std::shared_ptr<LcsClientExternal>>& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<AfExternal>>& getAfExternals();
    bool afExternalsIsSet() const;
    void unsetAfExternals();

    void setAfExternals(const std::vector<std::shared_ptr<AfExternal>>& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<LcsClientGroupExternal>>& getLcsClientGroupExternals();
    bool lcsClientGroupExternalsIsSet() const;
    void unsetLcsClientGroupExternals();

    void setLcsClientGroupExternals(const std::vector<std::shared_ptr<LcsClientGroupExternal>>& value);


protected:
    std::vector<std::shared_ptr<LcsClientExternal>> m_LcsClientExternals;
    bool m_LcsClientExternalsIsSet;
    std::vector<std::shared_ptr<AfExternal>> m_AfExternals;
    bool m_AfExternalsIsSet;
    std::vector<std::shared_ptr<LcsClientGroupExternal>> m_LcsClientGroupExternals;
    bool m_LcsClientGroupExternalsIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ExternalUnrelatedClass_H_ */
