/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * FrameRouteInfo.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_FrameRouteInfo_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_FrameRouteInfo_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  FrameRouteInfo
    : public ModelBase
{
public:
    FrameRouteInfo();
    virtual ~FrameRouteInfo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FrameRouteInfo members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getIpv4Mask() const;
    bool ipv4MaskIsSet() const;
    void unsetIpv4Mask();

    void setIpv4Mask(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getIpv6Prefix() const;
    bool ipv6PrefixIsSet() const;
    void unsetIpv6Prefix();

    void setIpv6Prefix(const utility::string_t& value);


protected:
    utility::string_t m_Ipv4Mask;
    bool m_Ipv4MaskIsSet;
    utility::string_t m_Ipv6Prefix;
    bool m_Ipv6PrefixIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_FrameRouteInfo_H_ */
