/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GroupIdentifiers.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_GroupIdentifiers_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_GroupIdentifiers_H_


#include "../ModelBase.h"

#include "UeId.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  GroupIdentifiers
    : public ModelBase
{
public:
    GroupIdentifiers();
    virtual ~GroupIdentifiers();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// GroupIdentifiers members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getExtGroupId() const;
    bool extGroupIdIsSet() const;
    void unsetExtGroupId();

    void setExtGroupId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getIntGroupId() const;
    bool intGroupIdIsSet() const;
    void unsetIntGroupId();

    void setIntGroupId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<UeId>>& getUeIdList();
    bool ueIdListIsSet() const;
    void unsetUeIdList();

    void setUeIdList(const std::vector<std::shared_ptr<UeId>>& value);


protected:
    utility::string_t m_ExtGroupId;
    bool m_ExtGroupIdIsSet;
    utility::string_t m_IntGroupId;
    bool m_IntGroupIdIsSet;
    std::vector<std::shared_ptr<UeId>> m_UeIdList;
    bool m_UeIdListIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_GroupIdentifiers_H_ */
