/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * JobType.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_JobType_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_JobType_H_


#include "../ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {

class  JobType
    : public ModelBase
{
public:
    JobType();
    virtual ~JobType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eJobType
    {
        JobType_IMMEDIATE_MDT_ONLY,
        JobType_LOGGED_MDT_ONLY,
        JobType_TRACE_ONLY,
        JobType_IMMEDIATE_MDT_AND_TRACE,
        JobType_RLF_REPORTS_ONLY,
        JobType_RCEF_REPORTS_ONLY,
        JobType_LOGGED_MBSFN_MDT,
    };

    eJobType getValue() const;
    void setValue(eJobType const value);

    protected:
        eJobType m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_JobType_H_ */
