/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "LcsClientClass.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



LcsClientClass::LcsClientClass()
{
}

LcsClientClass::~LcsClientClass()
{
}

void LcsClientClass::validate()
{
    // TODO: implement validation
}

web::json::value LcsClientClass::toJson() const
{
    web::json::value val = web::json::value::object();

    
    if (m_value == eLcsClientClass::LcsClientClass_BROADCAST_SERVICE) val = web::json::value::string(U(BROADCAST_SERVICE));
    if (m_value == eLcsClientClass::LcsClientClass_OM_IN_HPLMN) val = web::json::value::string(U(OM_IN_HPLMN));
    if (m_value == eLcsClientClass::LcsClientClass_OM_IN_VPLMN) val = web::json::value::string(U(OM_IN_VPLMN));
    if (m_value == eLcsClientClass::LcsClientClass_ANONYMOUS_LOCATION_SERVICE) val = web::json::value::string(U(ANONYMOUS_LOCATION_SERVICE));
    if (m_value == eLcsClientClass::LcsClientClass_SPECIFIC_SERVICE) val = web::json::value::string(U(SPECIFIC_SERVICE));

    return val;
}

bool LcsClientClass::fromJson(const web::json::value& val)
{
    auto s = val.as_string();

    
    if (s == utility::conversions::to_string_t(BROADCAST_SERVICE)) m_value = eLcsClientClass::LcsClientClass_BROADCAST_SERVICE;
    if (s == utility::conversions::to_string_t(OM_IN_HPLMN)) m_value = eLcsClientClass::LcsClientClass_OM_IN_HPLMN;
    if (s == utility::conversions::to_string_t(OM_IN_VPLMN)) m_value = eLcsClientClass::LcsClientClass_OM_IN_VPLMN;
    if (s == utility::conversions::to_string_t(ANONYMOUS_LOCATION_SERVICE)) m_value = eLcsClientClass::LcsClientClass_ANONYMOUS_LOCATION_SERVICE;
    if (s == utility::conversions::to_string_t(SPECIFIC_SERVICE)) m_value = eLcsClientClass::LcsClientClass_SPECIFIC_SERVICE;
    return true;
}

void LcsClientClass::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    utility::string_t s;

    
    if (m_value == eLcsClientClass::LcsClientClass_BROADCAST_SERVICE) s = utility::conversions::to_string_t(BROADCAST_SERVICE);
    if (m_value == eLcsClientClass::LcsClientClass_OM_IN_HPLMN) s = utility::conversions::to_string_t(OM_IN_HPLMN);
    if (m_value == eLcsClientClass::LcsClientClass_OM_IN_VPLMN) s = utility::conversions::to_string_t(OM_IN_VPLMN);
    if (m_value == eLcsClientClass::LcsClientClass_ANONYMOUS_LOCATION_SERVICE) s = utility::conversions::to_string_t(ANONYMOUS_LOCATION_SERVICE);
    if (m_value == eLcsClientClass::LcsClientClass_SPECIFIC_SERVICE) s = utility::conversions::to_string_t(SPECIFIC_SERVICE);

    multipart->add(ModelBase::toHttpContent(namePrefix, s));
}

bool LcsClientClass::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    {
        utility::string_t s;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), s);
        eLcsClientClass v;

        
        if (s == utility::conversions::to_string_t(BROADCAST_SERVICE)) v = eLcsClientClass::LcsClientClass_BROADCAST_SERVICE;
        if (s == utility::conversions::to_string_t(OM_IN_HPLMN)) v = eLcsClientClass::LcsClientClass_OM_IN_HPLMN;
        if (s == utility::conversions::to_string_t(OM_IN_VPLMN)) v = eLcsClientClass::LcsClientClass_OM_IN_VPLMN;
        if (s == utility::conversions::to_string_t(ANONYMOUS_LOCATION_SERVICE)) v = eLcsClientClass::LcsClientClass_ANONYMOUS_LOCATION_SERVICE;
        if (s == utility::conversions::to_string_t(SPECIFIC_SERVICE)) v = eLcsClientClass::LcsClientClass_SPECIFIC_SERVICE;

        setValue(v);
    }
    return ok;
}

LcsClientClass::eLcsClientClass LcsClientClass::getValue() const
{
   return m_value;
}

void LcsClientClass::setValue(LcsClientClass::eLcsClientClass const value)
{
   m_value = value;
}


}
}
}
}


