/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MeasurementNrForMdt.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_MeasurementNrForMdt_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_MeasurementNrForMdt_H_


#include "../ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {

class  MeasurementNrForMdt
    : public ModelBase
{
public:
    MeasurementNrForMdt();
    virtual ~MeasurementNrForMdt();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eMeasurementNrForMdt
    {
        MeasurementNrForMdt_M1,
        MeasurementNrForMdt_M2,
        MeasurementNrForMdt_M3,
        MeasurementNrForMdt_M4_DL,
        MeasurementNrForMdt_M4_UL,
        MeasurementNrForMdt_M5_DL,
        MeasurementNrForMdt_M5_UL,
        MeasurementNrForMdt_M6_DL,
        MeasurementNrForMdt_M6_UL,
        MeasurementNrForMdt_M7_DL,
        MeasurementNrForMdt_M7_UL,
        MeasurementNrForMdt_M8,
        MeasurementNrForMdt_M9,
    };

    eMeasurementNrForMdt getValue() const;
    void setValue(eMeasurementNrForMdt const value);

    protected:
        eMeasurementNrForMdt m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_MeasurementNrForMdt_H_ */
