/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * NiddInformation.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_NiddInformation_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_NiddInformation_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  NiddInformation
    : public ModelBase
{
public:
    NiddInformation();
    virtual ~NiddInformation();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// NiddInformation members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAfId() const;
    bool afIdIsSet() const;
    void unsetAfId();

    void setAfId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getGpsi() const;
    bool gpsiIsSet() const;
    void unsetGpsi();

    void setGpsi(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getExtGroupId() const;
    bool extGroupIdIsSet() const;
    void unsetExtGroupId();

    void setExtGroupId(const utility::string_t& value);


protected:
    utility::string_t m_AfId;
    bool m_AfIdIsSet;
    utility::string_t m_Gpsi;
    bool m_GpsiIsSet;
    utility::string_t m_ExtGroupId;
    bool m_ExtGroupIdIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_NiddInformation_H_ */
