/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "OperationMode.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



OperationMode::OperationMode()
{
}

OperationMode::~OperationMode()
{
}

void OperationMode::validate()
{
    // TODO: implement validation
}

web::json::value OperationMode::toJson() const
{
    web::json::value val = web::json::value::object();

    
    if (m_value == eOperationMode::OperationMode_WB_S1) val = web::json::value::string(U(WB_S1));
    if (m_value == eOperationMode::OperationMode_NB_S1) val = web::json::value::string(U(NB_S1));
    if (m_value == eOperationMode::OperationMode_WB_N1) val = web::json::value::string(U(WB_N1));
    if (m_value == eOperationMode::OperationMode_NB_N1) val = web::json::value::string(U(NB_N1));

    return val;
}

bool OperationMode::fromJson(const web::json::value& val)
{
    auto s = val.as_string();

    
    if (s == utility::conversions::to_string_t(WB_S1)) m_value = eOperationMode::OperationMode_WB_S1;
    if (s == utility::conversions::to_string_t(NB_S1)) m_value = eOperationMode::OperationMode_NB_S1;
    if (s == utility::conversions::to_string_t(WB_N1)) m_value = eOperationMode::OperationMode_WB_N1;
    if (s == utility::conversions::to_string_t(NB_N1)) m_value = eOperationMode::OperationMode_NB_N1;
    return true;
}

void OperationMode::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    utility::string_t s;

    
    if (m_value == eOperationMode::OperationMode_WB_S1) s = utility::conversions::to_string_t(WB_S1);
    if (m_value == eOperationMode::OperationMode_NB_S1) s = utility::conversions::to_string_t(NB_S1);
    if (m_value == eOperationMode::OperationMode_WB_N1) s = utility::conversions::to_string_t(WB_N1);
    if (m_value == eOperationMode::OperationMode_NB_N1) s = utility::conversions::to_string_t(NB_N1);

    multipart->add(ModelBase::toHttpContent(namePrefix, s));
}

bool OperationMode::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    {
        utility::string_t s;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), s);
        eOperationMode v;

        
        if (s == utility::conversions::to_string_t(WB_S1)) v = eOperationMode::OperationMode_WB_S1;
        if (s == utility::conversions::to_string_t(NB_S1)) v = eOperationMode::OperationMode_NB_S1;
        if (s == utility::conversions::to_string_t(WB_N1)) v = eOperationMode::OperationMode_WB_N1;
        if (s == utility::conversions::to_string_t(NB_N1)) v = eOperationMode::OperationMode_NB_N1;

        setValue(v);
    }
    return ok;
}

OperationMode::eOperationMode OperationMode::getValue() const
{
   return m_value;
}

void OperationMode::setValue(OperationMode::eOperationMode const value)
{
   m_value = value;
}


}
}
}
}


