/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "PlmnId.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




PlmnId::PlmnId()
{
    m_Mcc = utility::conversions::to_string_t("");
    m_MccIsSet = false;
    m_Mnc = utility::conversions::to_string_t("");
    m_MncIsSet = false;
}

PlmnId::~PlmnId()
{
}

void PlmnId::validate()
{
    // TODO: implement validation
}

web::json::value PlmnId::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_MccIsSet)
    {
        val[utility::conversions::to_string_t("mcc")] = ModelBase::toJson(m_Mcc);
    }
    if(m_MncIsSet)
    {
        val[utility::conversions::to_string_t("mnc")] = ModelBase::toJson(m_Mnc);
    }

    return val;
}

bool PlmnId::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t("mcc")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("mcc"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_mcc;
            ok &= ModelBase::fromJson(fieldValue, refVal_mcc);
            setMcc(refVal_mcc);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("mnc")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("mnc"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_mnc;
            ok &= ModelBase::fromJson(fieldValue, refVal_mnc);
            setMnc(refVal_mnc);
        }
    }
    return ok;
}

void PlmnId::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    if(m_MccIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("mcc"), m_Mcc));
    }
    if(m_MncIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("mnc"), m_Mnc));
    }
}

bool PlmnId::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("mcc")))
    {
        utility::string_t refVal_mcc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("mcc")), refVal_mcc );
        setMcc(refVal_mcc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("mnc")))
    {
        utility::string_t refVal_mnc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("mnc")), refVal_mnc );
        setMnc(refVal_mnc);
    }
    return ok;
}

utility::string_t PlmnId::getMcc() const
{
    return m_Mcc;
}

void PlmnId::setMcc(const utility::string_t& value)
{
    m_Mcc = value;
    m_MccIsSet = true;
}

bool PlmnId::mccIsSet() const
{
    return m_MccIsSet;
}

void PlmnId::unsetMcc()
{
    m_MccIsSet = false;
}
utility::string_t PlmnId::getMnc() const
{
    return m_Mnc;
}

void PlmnId::setMnc(const utility::string_t& value)
{
    m_Mnc = value;
    m_MncIsSet = true;
}

bool PlmnId::mncIsSet() const
{
    return m_MncIsSet;
}

void PlmnId::unsetMnc()
{
    m_MncIsSet = false;
}
}
}
}
}


