/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ReportAmountMdt.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ReportAmountMdt_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ReportAmountMdt_H_


#include "../ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {

class  ReportAmountMdt
    : public ModelBase
{
public:
    ReportAmountMdt();
    virtual ~ReportAmountMdt();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eReportAmountMdt
    {
        ReportAmountMdt__1,
        ReportAmountMdt__2,
        ReportAmountMdt__4,
        ReportAmountMdt__8,
        ReportAmountMdt__16,
        ReportAmountMdt__32,
        ReportAmountMdt__64,
        ReportAmountMdt_INFINITY,
    };

    eReportAmountMdt getValue() const;
    void setValue(eReportAmountMdt const value);

    protected:
        eReportAmountMdt m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ReportAmountMdt_H_ */
