/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UeId.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_UeId_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_UeId_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  UeId
    : public ModelBase
{
public:
    UeId();
    virtual ~UeId();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// UeId members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSupi() const;
    bool supiIsSet() const;
    void unsetSupi();

    void setSupi(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<utility::string_t>>& getGpsiList();
    bool gpsiListIsSet() const;
    void unsetGpsiList();

    void setGpsiList(const std::vector<std::shared_ptr<utility::string_t>>& value);


protected:
    utility::string_t m_Supi;
    bool m_SupiIsSet;
    std::vector<std::shared_ptr<utility::string_t>> m_GpsiList;
    bool m_GpsiListIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_UeId_H_ */
