/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 2.1.2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * WirelineServiceAreaRestriction.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_WirelineServiceAreaRestriction_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_WirelineServiceAreaRestriction_H_


#include "../ModelBase.h"

#include "RestrictionType.h"
#include "WirelineArea.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  WirelineServiceAreaRestriction
    : public ModelBase
{
public:
    WirelineServiceAreaRestriction();
    virtual ~WirelineServiceAreaRestriction();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// WirelineServiceAreaRestriction members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<RestrictionType> getRestrictionType() const;
    bool restrictionTypeIsSet() const;
    void unsetRestrictionType();

    void setRestrictionType(const std::shared_ptr<RestrictionType>& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<WirelineArea>>& getAreas();
    bool areasIsSet() const;
    void unsetAreas();

    void setAreas(const std::vector<std::shared_ptr<WirelineArea>>& value);


protected:
    std::shared_ptr<RestrictionType> m_RestrictionType;
    bool m_RestrictionTypeIsSet;
    std::vector<std::shared_ptr<WirelineArea>> m_Areas;
    bool m_AreasIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_WirelineServiceAreaRestriction_H_ */
