/**
 * Nucmf_UECapabilityManagement
 * Nucmf_UECapabilityManagement Service. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * DicEntryCreatedData.h
 *
 *
 */

#ifndef DicEntryCreatedData_H_
#define DicEntryCreatedData_H_

#include "jsonParser.hpp"
#include <string>
#include <type_traits>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class DicEntryCreatedData : public jsonParser::jsonParser<DicEntryCreatedData> {
public:
  explicit DicEntryCreatedData() {
    // constructor

    m_PlmnAssiUeRadioCapIdFlag = staticjson::Flags::Default;
  };
  virtual ~DicEntryCreatedData(){};

  void staticjson_init(staticjson::ObjectHandler *h) {

    // static json settings members vars : PlmnAssiUeRadioCapId
    h->add_property("plmnAssiUeRadioCapId", &this->m_PlmnAssiUeRadioCapId,
                    m_PlmnAssiUeRadioCapIdFlag);

    h->set_flags(staticjson::Flags::Default |
                 staticjson::Flags::DisallowUnknownKey);
  }
  template <typename T>
  static std::string convert2string(std::string name,
                                    const std::vector<T> &obj) {
    std::stringstream o;
    o << "name : ";
    for (auto it : obj) {
      o << it;
    }
    o << std::endl;

    return o.str();
  }

  template <typename T, typename T1>
  static std::string convert2string(std::string name,
                                    const std::map<T, T1> &obj) {
    std::stringstream out;
    out << "name : ";
    for (auto it : obj) {
      out << it.first << ":" << it.second << " ";
    }
    out << std::endl;
    return out.str();
  }

  friend std::ostream &operator<<(std::ostream &o,
                                  const DicEntryCreatedData &obj) {

    o << "PlmnAssiUeRadioCapId : " << obj.m_PlmnAssiUeRadioCapId << std::endl;

    return o;
  }

  /////////////////////////////////////////////
  /// DicEntryCreatedData members vars : PlmnAssiUeRadioCapId

  std::string getPlmnAssiUeRadioCapId() const { return m_PlmnAssiUeRadioCapId; }
  void setPlmnAssiUeRadioCapId(std::string const &value) {
    m_PlmnAssiUeRadioCapId = value;
  }

public:
  std::string m_PlmnAssiUeRadioCapId;

  unsigned m_PlmnAssiUeRadioCapIdFlag;
};
} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* DicEntryCreatedData_H_ */
