/**
 * Nucmf_UECapabilityManagement
 * Nucmf_UECapabilityManagement Service. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NFType.h
 *
 * NF types known to NRF
 */

#ifndef NFType_H_
#define NFType_H_

#include "jsonParser.hpp"
#include <type_traits>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// NF types known to NRF
/// </summary>
class NFType : public jsonParser::jsonParser<NFType> {
public:
  explicit NFType() {
    // constructor

    std::string m_NFType;
  };
  virtual ~NFType(){};

  std::pair<jsonRet, std::string> decode(const std::string &jsonBuffer,
                                         staticjson::ParseStatus &result) {
    std::pair<jsonRet, std::string> ret;
    m_NFType = jsonBuffer;
    return ret;
  }

  void staticjson_init(staticjson::ObjectHandler *h) {

    // static json settings members vars :

    h->set_flags(staticjson::Flags::Default |
                 staticjson::Flags::DisallowUnknownKey);
  }
  friend std::ostream &operator<<(std::ostream &o, const NFType &obj) {

    return o;
  }

public:
  std::string m_NFType;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* NFType_H_ */
