/**
 * Nucmf_UECapabilityManagement
 * Nucmf_UECapabilityManagement Service. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Snssai.h
 *
 *
 */

#ifndef Snssai_H_
#define Snssai_H_

#include "jsonParser.hpp"
#include <string>
#include <type_traits>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class Snssai : public jsonParser::jsonParser<Snssai> {
public:
  explicit Snssai() {
    // constructor
    m_Sst = 0;

    m_SstFlag = staticjson::Flags::Default;
    m_Sd = "";

    m_SdFlag = (staticjson::Flags::Optional);
  };
  virtual ~Snssai(){};

  void staticjson_init(staticjson::ObjectHandler *h) {

    // static json settings members vars : Sst Sd
    h->add_property("sst", &this->m_Sst, m_SstFlag);
    h->add_property("sd", &this->m_Sd, m_SdFlag);

    h->set_flags(staticjson::Flags::Default |
                 staticjson::Flags::DisallowUnknownKey);
  }
  template <typename T>
  static std::string convert2string(std::string name,
                                    const std::vector<T> &obj) {
    std::stringstream o;
    o << "name : ";
    for (auto it : obj) {
      o << it;
    }
    o << std::endl;

    return o.str();
  }

  template <typename T, typename T1>
  static std::string convert2string(std::string name,
                                    const std::map<T, T1> &obj) {
    std::stringstream out;
    out << "name : ";
    for (auto it : obj) {
      out << it.first << ":" << it.second << " ";
    }
    out << std::endl;
    return out.str();
  }

  friend std::ostream &operator<<(std::ostream &o, const Snssai &obj) {

    o << "Sst : " << obj.m_Sst << std::endl;

    o << "Sd : " << obj.m_Sd << std::endl;

    return o;
  }

  /////////////////////////////////////////////
  /// Snssai members vars : Sst Sd

  int32_t getSst() const { return m_Sst; }
  void setSst(int32_t const value) { m_Sst = value; }

  std::string getSd() const { return m_Sd; }
  void setSd(std::string const &value) { m_Sd = value; }

public:
  int32_t m_Sst;

  unsigned m_SstFlag;
  std::string m_Sd;

  unsigned m_SdFlag;
};
} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* Snssai_H_ */
