/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Area.h
 *
 * 
 */

#ifndef Area_H_
#define Area_H_


#include <string>
#include <vector>
#include "jsonParser/jsonParser.hpp"
#include <type_traits>
	
namespace org {
namespace openapitools {
namespace server {
namespace model {


    

/// <summary>
/// 
/// </summary>
class  Area: public jsonParser::jsonParser<Area>
{
public:
    explicit Area(){
        // constructor
        
            m_TacsFlag = (staticjson::Flags::Optional);
m_AreaCode = "";
        
            m_AreaCodeFlag = (staticjson::Flags::Optional);
    };
    virtual ~Area(){};

  

    void staticjson_init(staticjson::ObjectHandler *h)
    {

        // static json settings members vars : Tacs AreaCode 
        h->add_property("tacs", &this->m_Tacs, m_TacsFlag);
        h->add_property("areaCode", &this->m_AreaCode, m_AreaCodeFlag);



        h->set_flags(staticjson::Flags::Default | staticjson::Flags::DisallowUnknownKey);
    }
    template<typename T>
    static std::string convert2string(std::string name ,const std::vector<T>& obj){
         std::stringstream o;
         o << "name : ";
            for(auto it : obj)
            {
                o<< it;
            }
            o<<std::endl;

            return o.str();

    }

    template<typename T, typename T1>
    static std::string convert2string(std::string name ,const std::map<T,T1>& obj){
        std::stringstream out;
            out<<"name : ";
            for(auto it : obj)
            {
                out<< it.first<<":"<<it.second<<" ";
            }
            out<<std::endl;
            return out.str();

    }

    friend std::ostream& operator<<(std::ostream& o, const Area& obj)
    {
                o<< convert2string(std::string("Tacs"), obj.m_Tacs) <<std::endl;
       
        o << "AreaCode : " << obj.m_AreaCode << std::endl;

     
        return o;
    }

    /////////////////////////////////////////////
    /// Area members vars : Tacs AreaCode 

    std::vector<std::string>&  getTacs()
    {
        return m_Tacs;
    }
    void  setTacs(std::vector<std::string> const& value)
    {
        m_Tacs = value;
    }

std::string  getAreaCode() const
    {
        return m_AreaCode;
    }
    void  setAreaCode(std::string const& value)
    {
        m_AreaCode = value;
    }



    
public:
    std::vector<std::string> m_Tacs;
    
    unsigned m_TacsFlag;
    std::string m_AreaCode;
    
    unsigned m_AreaCodeFlag;
  
};
}
}
}
}

#endif /* Area_H_ */
