/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Polygon.h
 *
 * 
 */

#ifndef Polygon_H_
#define Polygon_H_


#include "GeographicalCoordinates.h"
#include "GADShape.h"
#include <vector>
#include "Polygon_allOf.h"
#include "SupportedGADShapes.h"
#include "jsonParser/jsonParser.hpp"
#include <type_traits>
	
namespace org {
namespace openapitools {
namespace server {
namespace model {


    

/// <summary>
/// 
/// </summary>
class  Polygon: public jsonParser::jsonParser<Polygon>
{
public:
    explicit Polygon(){
        // constructor
        
            m_ShapeFlag = staticjson::Flags::Default;

            m_PointListFlag = staticjson::Flags::Default;
    };
    virtual ~Polygon(){};

  

    void staticjson_init(staticjson::ObjectHandler *h)
    {

        // static json settings members vars : Shape PointList 
        h->add_property("shape", &this->m_Shape, m_ShapeFlag);
        h->add_property("pointList", &this->m_PointList, m_PointListFlag);



        h->set_flags(staticjson::Flags::Default | staticjson::Flags::DisallowUnknownKey);
    }
    template<typename T>
    static std::string convert2string(std::string name ,const std::vector<T>& obj){
         std::stringstream o;
         o << "name : ";
            for(auto it : obj)
            {
                o<< it;
            }
            o<<std::endl;

            return o.str();

    }

    template<typename T, typename T1>
    static std::string convert2string(std::string name ,const std::map<T,T1>& obj){
        std::stringstream out;
            out<<"name : ";
            for(auto it : obj)
            {
                out<< it.first<<":"<<it.second<<" ";
            }
            out<<std::endl;
            return out.str();

    }

    friend std::ostream& operator<<(std::ostream& o, const Polygon& obj)
    {
        
        o << "Shape : " << obj.m_Shape << std::endl;
        o<< convert2string(std::string("PointList"), obj.m_PointList) <<std::endl;
       
     
        return o;
    }

    /////////////////////////////////////////////
    /// Polygon members vars : Shape PointList 

    SupportedGADShapes  getShape() const
    {
        return m_Shape;
    }
    void  setShape(SupportedGADShapes const& value)
    {
        m_Shape = value;
    }

std::vector<GeographicalCoordinates>&  getPointList()
    {
        return m_PointList;
    }
    void  setPointList(std::vector<GeographicalCoordinates> const& value)
    {
        m_PointList = value;
    }



    
public:
    SupportedGADShapes m_Shape;
    
    unsigned m_ShapeFlag;
    std::vector<GeographicalCoordinates> m_PointList;
    
    unsigned m_PointListFlag;
  
};
}
}
}
}

#endif /* Polygon_H_ */
