/**
* Nudm_SDM
* Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 2.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SteeringContainer.h
 *
 * 
 */

#ifndef SteeringContainer_H_
#define SteeringContainer_H_


#include "jsonParser/jsonParser.hpp"
#include <type_traits>
	
namespace org {
namespace openapitools {
namespace server {
namespace model {


    

/// <summary>
/// 
/// </summary>
class  SteeringContainer: public jsonParser::jsonParser<SteeringContainer>
{
public:
    explicit SteeringContainer(){
        // constructor
            };
    virtual ~SteeringContainer(){};

  

    void staticjson_init(staticjson::ObjectHandler *h)
    {

        // static json settings members vars : 



        h->set_flags(staticjson::Flags::Default | staticjson::Flags::DisallowUnknownKey);
    }
    template<typename T>
    static std::string convert2string(std::string name ,const std::vector<T>& obj){
         std::stringstream o;
         o << "name : ";
            for(auto it : obj)
            {
                o<< it;
            }
            o<<std::endl;

            return o.str();

    }

    template<typename T, typename T1>
    static std::string convert2string(std::string name ,const std::map<T,T1>& obj){
        std::stringstream out;
            out<<"name : ";
            for(auto it : obj)
            {
                out<< it.first<<":"<<it.second<<" ";
            }
            out<<std::endl;
            return out.str();

    }

    friend std::ostream& operator<<(std::ostream& o, const SteeringContainer& obj)
    {
        
     
        return o;
    }

    /////////////////////////////////////////////
    /// SteeringContainer members vars : 

    

    
public:
  
};
}
}
}
}

#endif /* SteeringContainer_H_ */
