/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * RatType.h
 *
 * 
 */

#ifndef RatType_H_
#define RatType_H_


#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  RatType
{
public:
    RatType();
    virtual ~RatType();

    enum class eRatType {
    // To have a valid default value.
    // Avoiding nameclashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    NR, 
    EUTRA, 
    WLAN, 
    VIRTUAL, 
    NBIOT, 
    WIRELINE, 
    WIRELINE_CABLE, 
    WIRELINE_BBF, 
    LTE_M, 
    NR_U, 
    EUTRA_U, 
    TRUSTED_N3GA, 
    TRUSTED_WLAN, 
    UTRA, 
    GERA
    };
    void validate();

    /////////////////////////////////////////////
    /// RatType members

    RatType::eRatType getValue() const;
    void setValue(RatType::eRatType value);

    friend void to_json(nlohmann::json& j, const RatType& o);
    friend void from_json(const nlohmann::json& j, RatType& o);
protected:
    RatType::eRatType m_value = RatType::eRatType::INVALID_VALUE_OPENAPI_GENERATED;
};

}
}
}
}

#endif /* RatType_H_ */
