/**
* Nudm_UECM
* Nudm Context Management Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * RegistrationDataSetName_anyOf.h
 *
 * 
 */

#ifndef RegistrationDataSetName_anyOf_H_
#define RegistrationDataSetName_anyOf_H_


#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  RegistrationDataSetName_anyOf
{
public:
    RegistrationDataSetName_anyOf();
    virtual ~RegistrationDataSetName_anyOf();

    enum class eRegistrationDataSetName_anyOf {
    // To have a valid default value.
    // Avoiding nameclashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    AMF_3GPP, 
    AMF_NON_3GPP, 
    SMF_PDU_SESSIONS, 
    SMSF_3GPP, 
    SMSF_NON_3GPP
    };
    void validate();

    /////////////////////////////////////////////
    /// RegistrationDataSetName_anyOf members

    RegistrationDataSetName_anyOf::eRegistrationDataSetName_anyOf getValue() const;
    void setValue(RegistrationDataSetName_anyOf::eRegistrationDataSetName_anyOf value);

    friend void to_json(nlohmann::json& j, const RegistrationDataSetName_anyOf& o);
    friend void from_json(const nlohmann::json& j, RegistrationDataSetName_anyOf& o);
protected:
    RegistrationDataSetName_anyOf::eRegistrationDataSetName_anyOf m_value = RegistrationDataSetName_anyOf::eRegistrationDataSetName_anyOf::INVALID_VALUE_OPENAPI_GENERATED;
};

}
}
}
}

#endif /* RegistrationDataSetName_anyOf_H_ */
