/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * EllipsoidArc_allOf.h
 *
 *
 * if you need to add new attribure, please contact max.cong@nokia-sbell.com to
 * generate new code.
 */

#ifndef EllipsoidArc_allOf_H_
#define EllipsoidArc_allOf_H_

#include "CSB_JsonParser.h"
#include "GeographicalCoordinates.h"
#include <type_traits>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class EllipsoidArc_allOf : public jsonParser::jsonParser<EllipsoidArc_allOf> {
public:
  explicit EllipsoidArc_allOf() {
    // constructor

    m_PointFlag = staticjson::Flags::Default;
    m_PointOutFlag.reset(new unsigned);
    *m_PointOutFlag.get() = 0;
    m_InnerRadius = 0;

    m_InnerRadiusFlag = staticjson::Flags::Default;
    m_InnerRadiusOutFlag.reset(new unsigned);
    *m_InnerRadiusOutFlag.get() = 0;
    m_UncertaintyRadius = 0.0f;

    m_UncertaintyRadiusFlag = staticjson::Flags::Default;
    m_UncertaintyRadiusOutFlag.reset(new unsigned);
    *m_UncertaintyRadiusOutFlag.get() = 0;
    m_OffsetAngle = 0;

    m_OffsetAngleFlag = staticjson::Flags::Default;
    m_OffsetAngleOutFlag.reset(new unsigned);
    *m_OffsetAngleOutFlag.get() = 0;
    m_IncludedAngle = 0;

    m_IncludedAngleFlag = staticjson::Flags::Default;
    m_IncludedAngleOutFlag.reset(new unsigned);
    *m_IncludedAngleOutFlag.get() = 0;
    m_Confidence = 0;

    m_ConfidenceFlag = staticjson::Flags::Default;
    m_ConfidenceOutFlag.reset(new unsigned);
    *m_ConfidenceOutFlag.get() = 0;
  };
  virtual ~EllipsoidArc_allOf(){};

  void staticjson_init(staticjson::ObjectHandler *h) {

    // static json settings members vars : Point InnerRadius UncertaintyRadius
    // OffsetAngle IncludedAngle Confidence
    h->add_property("point", &this->m_Point, m_PointFlag);
    h->add_property("innerRadius", &this->m_InnerRadius, m_InnerRadiusFlag);
    h->add_property("uncertaintyRadius", &this->m_UncertaintyRadius,
                    m_UncertaintyRadiusFlag);
    h->add_property("offsetAngle", &this->m_OffsetAngle, m_OffsetAngleFlag);
    h->add_property("includedAngle", &this->m_IncludedAngle,
                    m_IncludedAngleFlag);
    h->add_property("confidence", &this->m_Confidence, m_ConfidenceFlag);

    h->set_flags(staticjson::Flags::Default |
                 staticjson::Flags::DisallowUnknownKey);
  }
  template <typename T>
  static std::string convert2string(std::string name,
                                    const std::vector<T> &obj) {
    std::stringstream o;
    o << "name : ";
    for (auto it : obj) {
      o << it;
    }
    o << std::endl;

    return o.str();
  }

  template <typename T, typename T1>
  static std::string convert2string(std::string name,
                                    const std::map<T, T1> &obj) {
    std::stringstream out;
    out << "name : ";
    for (auto it : obj) {
      out << it.first << ":" << it.second << " ";
    }
    out << std::endl;
    return out.str();
  }

  friend std::ostream &operator<<(std::ostream &o,
                                  const EllipsoidArc_allOf &obj) {

    o << "Point : " << obj.m_Point << std::endl;

    o << "InnerRadius : " << obj.m_InnerRadius << std::endl;

    o << "UncertaintyRadius : " << obj.m_UncertaintyRadius << std::endl;

    o << "OffsetAngle : " << obj.m_OffsetAngle << std::endl;

    o << "IncludedAngle : " << obj.m_IncludedAngle << std::endl;

    o << "Confidence : " << obj.m_Confidence << std::endl;

    return o;
  }

  /////////////////////////////////////////////
  /// EllipsoidArc_allOf members vars : Point InnerRadius UncertaintyRadius
  /// OffsetAngle IncludedAngle Confidence

  GeographicalCoordinates getPoint() const { return m_Point; }
  void setPoint(GeographicalCoordinates const &value) { m_Point = value; }

  int32_t getInnerRadius() const { return m_InnerRadius; }
  void setInnerRadius(int32_t const value) { m_InnerRadius = value; }

  float getUncertaintyRadius() const { return m_UncertaintyRadius; }
  void setUncertaintyRadius(float const value) { m_UncertaintyRadius = value; }

  int32_t getOffsetAngle() const { return m_OffsetAngle; }
  void setOffsetAngle(int32_t const value) { m_OffsetAngle = value; }

  int32_t getIncludedAngle() const { return m_IncludedAngle; }
  void setIncludedAngle(int32_t const value) { m_IncludedAngle = value; }

  int32_t getConfidence() const { return m_Confidence; }
  void setConfidence(int32_t const value) { m_Confidence = value; }

public:
  GeographicalCoordinates m_Point;

  unsigned m_PointFlag;
  shared_ptr<unsigned> m_PointOutFlag;
  int32_t m_InnerRadius;

  unsigned m_InnerRadiusFlag;
  shared_ptr<unsigned> m_InnerRadiusOutFlag;
  float m_UncertaintyRadius;

  unsigned m_UncertaintyRadiusFlag;
  shared_ptr<unsigned> m_UncertaintyRadiusOutFlag;
  int32_t m_OffsetAngle;

  unsigned m_OffsetAngleFlag;
  shared_ptr<unsigned> m_OffsetAngleOutFlag;
  int32_t m_IncludedAngle;

  unsigned m_IncludedAngleFlag;
  shared_ptr<unsigned> m_IncludedAngleOutFlag;
  int32_t m_Confidence;

  unsigned m_ConfidenceFlag;
  shared_ptr<unsigned> m_ConfidenceOutFlag;
};
} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* EllipsoidArc_allOf_H_ */
