/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PlmnId.h
 *
 *
 * if you need to add new attribure, please contact max.cong@nokia-sbell.com to
 * generate new code.
 */

#ifndef PlmnId_H_
#define PlmnId_H_

#include "CSB_JsonParser.h"
#include <string>
#include <type_traits>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class PlmnId : public jsonParser::jsonParser<PlmnId> {
public:
  explicit PlmnId() {
    // constructor
    m_Mcc = "";

    m_MccFlag = staticjson::Flags::Default;
    m_MccOutFlag.reset(new unsigned);
    *m_MccOutFlag.get() = 0;
    m_Mnc = "";

    m_MncFlag = staticjson::Flags::Default;
    m_MncOutFlag.reset(new unsigned);
    *m_MncOutFlag.get() = 0;
  };
  virtual ~PlmnId(){};

  void staticjson_init(staticjson::ObjectHandler *h) {

    // static json settings members vars : Mcc Mnc
    h->add_property("mcc", &this->m_Mcc, m_MccFlag);
    h->add_property("mnc", &this->m_Mnc, m_MncFlag);

    h->set_flags(staticjson::Flags::Default |
                 staticjson::Flags::DisallowUnknownKey);
  }
  template <typename T>
  static std::string convert2string(std::string name,
                                    const std::vector<T> &obj) {
    std::stringstream o;
    o << "name : ";
    for (auto it : obj) {
      o << it;
    }
    o << std::endl;

    return o.str();
  }

  template <typename T, typename T1>
  static std::string convert2string(std::string name,
                                    const std::map<T, T1> &obj) {
    std::stringstream out;
    out << "name : ";
    for (auto it : obj) {
      out << it.first << ":" << it.second << " ";
    }
    out << std::endl;
    return out.str();
  }

  friend std::ostream &operator<<(std::ostream &o, const PlmnId &obj) {

    o << "Mcc : " << obj.m_Mcc << std::endl;

    o << "Mnc : " << obj.m_Mnc << std::endl;

    return o;
  }

  /////////////////////////////////////////////
  /// PlmnId members vars : Mcc Mnc

  std::string getMcc() const { return m_Mcc; }
  void setMcc(std::string const &value) { m_Mcc = value; }

  std::string getMnc() const { return m_Mnc; }
  void setMnc(std::string const &value) { m_Mnc = value; }

public:
  std::string m_Mcc;

  unsigned m_MccFlag;
  shared_ptr<unsigned> m_MccOutFlag;
  std::string m_Mnc;

  unsigned m_MncFlag;
  shared_ptr<unsigned> m_MncOutFlag;
};
} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* PlmnId_H_ */
