/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * RatType.h
 *
 *
 * if you need to add new attribure, please contact max.cong@nokia-sbell.com to
 * generate new code.
 */

#ifndef RatType_H_
#define RatType_H_

#include "CSB_JsonParser.h"
#include <type_traits>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class RatType : public jsonParser::jsonParser<RatType> {
public:
  explicit RatType(){
      // constructor

  };
  virtual ~RatType(){};

  std::pair<jsonRet, std::string> decode(const std::string &jsonBuffer,
                                         staticjson::ParseStatus &result) {
    std::pair<jsonRet, std::string> ret;
    m_RatType = jsonBuffer;
    return ret;
  }

  void staticjson_init(staticjson::ObjectHandler *h) {

    // static json settings members vars :

    h->set_flags(staticjson::Flags::Default |
                 staticjson::Flags::DisallowUnknownKey);
  }
  friend std::ostream &operator<<(std::ostream &o, const RatType &obj) {

    return o;
  }

public:
  std::string m_RatType;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* RatType_H_ */
