/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2020, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * UeContextInAmfData.h
 *
 *
 * if you need to add new attribure, please contact max.cong@nokia-sbell.com to
 * generate new code.
 */

#ifndef UeContextInAmfData_H_
#define UeContextInAmfData_H_

#include "CSB_JsonParser.h"
#include "EpsInterworkingInfo.h"
#include <type_traits>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class UeContextInAmfData : public jsonParser::jsonParser<UeContextInAmfData> {
public:
  explicit UeContextInAmfData() {
    // constructor

    m_EpsInterworkingInfoFlag =
        (staticjson::Flags::Optional | staticjson::Flags::IgnoreWrite);
    m_EpsInterworkingInfoOutFlag.reset(new unsigned);
    *m_EpsInterworkingInfoOutFlag.get() = 0;
  };
  virtual ~UeContextInAmfData(){};

  void staticjson_init(staticjson::ObjectHandler *h) {

    // static json settings members vars : EpsInterworkingInfo
    h->add_optional_property(
        "epsInterworkingInfo", &this->m_EpsInterworkingInfo,
        m_EpsInterworkingInfoFlag, m_EpsInterworkingInfoOutFlag);

    h->set_flags(staticjson::Flags::Default |
                 staticjson::Flags::DisallowUnknownKey);
  }
  template <typename T>
  static std::string convert2string(std::string name,
                                    const std::vector<T> &obj) {
    std::stringstream o;
    o << "name : ";
    for (auto it : obj) {
      o << it;
    }
    o << std::endl;

    return o.str();
  }

  template <typename T, typename T1>
  static std::string convert2string(std::string name,
                                    const std::map<T, T1> &obj) {
    std::stringstream out;
    out << "name : ";
    for (auto it : obj) {
      out << it.first << ":" << it.second << " ";
    }
    out << std::endl;
    return out.str();
  }

  friend std::ostream &operator<<(std::ostream &o,
                                  const UeContextInAmfData &obj) {

    o << "EpsInterworkingInfo, optional flag is : "
      << *m_EpsInterworkingInfoOutFlag
      << ", content is : " << obj.m_EpsInterworkingInfo << std::endl;

    return o;
  }

  /////////////////////////////////////////////
  /// UeContextInAmfData members vars : EpsInterworkingInfo

  EpsInterworkingInfo getEpsInterworkingInfo() const {
    return m_EpsInterworkingInfo;
  }
  void setEpsInterworkingInfo(EpsInterworkingInfo const &value) {
    m_EpsInterworkingInfo = value;
  }

public:
  EpsInterworkingInfo m_EpsInterworkingInfo;

  unsigned m_EpsInterworkingInfoFlag;
  shared_ptr<unsigned> m_EpsInterworkingInfoOutFlag;
};
} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* UeContextInAmfData_H_ */
